airflow:
  config:
    AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow_user:airflow_pass@psql-tysonium-centralus-dev.postgres.database.azure.com:5432/airflow_db
  
  dags:
    initContainer:
      enabled: true
    persistence:
      enabled: false
    image: 
      repository: acrtysoniumdev1.azurecr.io/airflow-dags 
      tag: latest
    volume:
      enabled: false

  image:
    repository: acrtysoniumdev1.azurecr.io/airflow
    tag: latest  # Replace with your desired version
    pullPolicy: IfNotPresent
  
  postgresql:
    enabled: false

persistence:
  enabled: true
  storageClassName: default

# Consider using a distributed executor for production
executor: LocalExecutor 

webserverSecretKey: 9dd318fc0e35da421e430ff29ad44dca

pgbouncer:
  enabled: true
  # The maximum number of connections to PgBouncer
  maxClientConn: 50
  # The maximum number of server connections to the metadata database from PgBouncer
  metadataPoolSize: 5
  # The maximum number of server connections to the result backend database from PgBouncer
  resultBackendPoolSize: 2